// Generated by scripts/build-pages.js. Do not edit by hand.
(function () {
  const sources = {
    "./config": function (require, module, exports) {
const range = (start, end) => Array.from({ length: end - start + 1 }, (_, i) => start + i);

const STAGE_LABELS = {
  group: 'Fase de grupos',
  round32: 'Dieciseisavos',
  round16: 'Octavos',
  quarter: 'Cuartos',
  semi: 'Semifinales',
  third: '3º y 4º puesto',
  final: 'Final',
  honor: 'Cuadro de honor',
  awards: 'Premios individuales'
};

// Puntuación introducida desde las capturas compartidas por Rodrigo.
// Exacto sustituye al signo: un resultado exacto de fase de grupos da 2 puntos, no 1+2.
const POINTS = {
  match: {
    group: { sign: 1, goalDiff: 0, exact: 2 },
    round32: { sign: 0, goalDiff: 0, exact: 2 },
    round16: { sign: 0, goalDiff: 0, exact: 2 },
    quarter: { sign: 0, goalDiff: 0, exact: 2 },
    semi: { sign: 0, goalDiff: 0, exact: 2 },
    third: { sign: 0, goalDiff: 0, exact: 0 },
    final: { sign: 0, goalDiff: 0, exact: 2 }
  },
  groupPosition: 1,
  qualifiedRound32: 1,
  qualifiedRound16: 1,
  qualifiedQuarter: 1,
  qualifiedSemi: 1,
  qualifiedThirdPlaceGame: 0,
  qualifiedFinal: 1,
  champion: 4,
  runnerUp: 1,
  thirdPlace: 0,
  goldenBoot: { gold: 2, silver: 0, bronze: 0 },
  goldenBall: { gold: 2, silver: 0, bronze: 0 }
};

const MATCH_ROWS = [
  ...range(6, 77).map((row, i) => ({ row, matchNumber: i + 1, stage: 'group' })),
  ...range(164, 179).map((row, i) => ({ row, matchNumber: 73 + i, stage: 'round32' })),
  ...range(200, 207).map((row, i) => ({ row, matchNumber: 89 + i, stage: 'round16' })),
  ...range(220, 223).map((row, i) => ({ row, matchNumber: 97 + i, stage: 'quarter' })),
  ...range(232, 233).map((row, i) => ({ row, matchNumber: 101 + i, stage: 'semi' })),
  { row: 244, matchNumber: 103, stage: 'third' },
  { row: 247, matchNumber: 104, stage: 'final' }
];

const QUALIFIER_ROWS = {
  round32: range(130, 161),
  round16: range(182, 197),
  quarter: range(210, 217),
  semi: range(226, 229),
  thirdPlaceGame: range(236, 237),
  final: range(240, 241)
};

const PODIUM_ROWS = {
  champion: 250,
  runnerUp: 251,
  thirdPlace: 252
};

const AWARD_ROWS = {
  goldenBoot: { gold: 253, silver: 254, bronze: 255 },
  goldenBall: { gold: 256, silver: 257, bronze: 258 }
};

const GROUP_POSITION_ROWS = range(80, 127);

module.exports = {
  STAGE_LABELS,
  POINTS,
  MATCH_ROWS,
  QUALIFIER_ROWS,
  GROUP_POSITION_ROWS,
  PODIUM_ROWS,
  AWARD_ROWS
};

    },
    "./utils": function (require, module, exports) {
function toText(value) {
  if (value === null || value === undefined) return '';
  return String(value).replace(/\s+/g, ' ').trim();
}

function removeAccents(value) {
  return toText(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

function normalizeText(value) {
  return removeAccents(value)
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

const ALIASES = new Map();
function addCanonical(canonical, aliases) {
  [canonical, ...aliases].forEach((alias) => ALIASES.set(normalizeText(alias), canonical));
}

addCanonical('Mexico', ['México', 'MEX', 'Mex']);
addCanonical('South Africa', ['Sudáfrica', 'Southafrica', 'RSA', 'Sud']);
addCanonical('South Korea', ['Corea del Sur', 'Korea Republic', 'Republic of Korea', 'Cor', 'KOR']);
addCanonical('Czech Republic', ['República Checa', 'Czechia', 'Rep', 'CZE']);
addCanonical('Canada', ['Canadá', 'Can', 'CAN']);
addCanonical('Bosnia and Herzegovina', ['Bosnia y Herzegovina', 'Bosnia-Herzegovina', 'Bosnia', 'Bos', 'BIH']);
addCanonical('Qatar', ['Catar', 'Cat', 'QAT']);
addCanonical('Switzerland', ['Suiza', 'Sui', 'SUI']);
addCanonical('Brazil', ['Brasil', 'Bra', 'BRA']);
addCanonical('Morocco', ['Marruecos', 'Mar', 'MAR']);
addCanonical('Haiti', ['Haití', 'Hai', 'HAI']);
addCanonical('Scotland', ['Escocia', 'Esc', 'SCO']);
addCanonical('USA', ['Estados Unidos', 'United States', 'USMNT', 'Est', 'USA']);
addCanonical('Paraguay', ['Par', 'PAR']);
addCanonical('Australia', ['Aus', 'AUS']);
addCanonical('Turkey', ['Turquía', 'Türkiye', 'Turkiye', 'Tur', 'TUR']);
addCanonical('Germany', ['Alemania', 'Ale', 'GER']);
addCanonical('Curacao', ['Curazao', 'Curaçao', 'Cur', 'CUW']);
addCanonical('Ivory Coast', ['Costa de Marfil', "Côte d'Ivoire", 'Cote d Ivoire', 'CIV']);
addCanonical('Ecuador', ['Ecu', 'ECU']);
addCanonical('Netherlands', ['Países Bajos', 'Paises Bajos', 'Holanda', 'Ned', 'NED']);
addCanonical('Japan', ['Japón', 'Japon', 'Jap', 'JPN']);
addCanonical('Sweden', ['Suecia', 'Swe', 'SWE']);
addCanonical('Tunisia', ['Túnez', 'Tunez', 'Tun', 'TUN']);
addCanonical('Belgium', ['Bélgica', 'Belgica', 'Bel', 'BEL']);
addCanonical('Egypt', ['Egipto', 'Egi', 'EGY']);
addCanonical('Iran', ['Irán', 'Irn', 'IRN']);
addCanonical('New Zealand', ['Nueva Zelanda', 'Nue', 'NZL']);
addCanonical('Spain', ['España', 'Espana', 'Esp', 'SPA', 'ESP']);
addCanonical('Cape Verde', ['Cabo Verde', 'Cap', 'CPV']);
addCanonical('Saudi Arabia', ['Arabia Saudita', 'Saudi', 'KSA', 'Sau']);
addCanonical('Uruguay', ['Uru', 'URU']);
addCanonical('France', ['Francia', 'Fra', 'FRA']);
addCanonical('Senegal', ['Sen', 'SEN']);
addCanonical('Iraq', ['Irak', 'Irq', 'IRQ']);
addCanonical('Norway', ['Noruega', 'Nor', 'NOR']);
addCanonical('Argentina', ['Arg', 'ARG']);
addCanonical('Algeria', ['Argelia', 'Alg', 'ALG']);
addCanonical('Austria', ['Aut', 'AUStria', 'AUT']);
addCanonical('Jordan', ['Jordania', 'Jor', 'JOR']);
addCanonical('Portugal', ['Por', 'POR']);
addCanonical('DR Congo', ['RD Congo', 'D.R. Congo', 'Congo DR', 'COD', 'RDC']);
addCanonical('Uzbekistan', ['Uzbekistán', 'Uzb', 'UZB']);
addCanonical('Colombia', ['Col', 'COL']);
addCanonical('England', ['Inglaterra', 'Ing', 'ENG']);
addCanonical('Croatia', ['Croacia', 'Cro', 'CRO']);
addCanonical('Ghana', ['Gha', 'GHA']);
addCanonical('Panama', ['Panamá', 'Panama', 'Pan', 'PAN']);

function canonicalTeamName(value) {
  const raw = toText(value)
    .replace(/^[🥇🥈🥉\s]+/u, '')
    .replace(/\([^)]*\)/g, '')
    .trim();
  const norm = normalizeText(raw);
  if (!norm) return '';
  return ALIASES.get(norm) || raw;
}

function teamKey(value) {
  return normalizeText(canonicalTeamName(value));
}

function sameTeam(a, b) {
  return teamKey(a) !== '' && teamKey(a) === teamKey(b);
}

function isPlaceholderTeam(value) {
  const text = toText(value);
  const norm = normalizeText(text);
  if (!text) return true;
  if (norm.includes('grupo') || norm.includes('finalista') || norm.includes('escribe un jugador')) return true;
  if (/^[wl](f|\d*)$/i.test(text)) return true;
  if (/^w[0-9]+$/i.test(text) || /^l[0-9]+$/i.test(text)) return true;
  if (/^\d+[a-l]$/i.test(text)) return true;
  if (/^\d+[a-l]{2,}$/i.test(text)) return true;
  if (/^[a-l]$/i.test(text)) return true;
  if (/^[0-9]+º/.test(text)) return true;
  if (/^[0-9]+\|/.test(text)) return true;
  return false;
}

function isRealTeam(value) {
  return !isPlaceholderTeam(value);
}

function asNumber(value) {
  if (value === null || value === undefined || value === '') return null;
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  const n = Number(String(value).replace(',', '.'));
  return Number.isFinite(n) ? n : null;
}

function signFromScores(home, away) {
  const h = asNumber(home);
  const a = asNumber(away);
  if (h === null || a === null) return '';
  if (h > a) return '1';
  if (h < a) return '2';
  return 'X';
}

function goalDiff(home, away) {
  const h = asNumber(home);
  const a = asNumber(away);
  if (h === null || a === null) return null;
  return h - a;
}

function parseScorePrediction(value) {
  const raw = toText(value);
  if (!raw) return { raw, valid: false, sign: '', homeGoals: null, awayGoals: null, prefix: '' };

  let prefix = '';
  let scoreText = raw;
  if (raw.includes('·')) {
    const parts = raw.split('·');
    prefix = parts.slice(0, -1).join('·');
    scoreText = parts.at(-1);
  }

  const [signPart = '', scorePart = ''] = scoreText.split('|');
  const sign = toText(signPart).toUpperCase().replace('EMPATE', 'X');
  let homeGoals = null;
  let awayGoals = null;
  if (scorePart && scorePart.includes('-')) {
    const [h, a] = scorePart.split('-');
    homeGoals = asNumber(h);
    awayGoals = asNumber(a);
  }

  const valid = homeGoals !== null && awayGoals !== null && ['1', 'X', '2'].includes(signFromScores(homeGoals, awayGoals));
  return {
    raw,
    prefix,
    scoreText,
    sign: ['1', 'X', '2'].includes(sign) ? sign : signFromScores(homeGoals, awayGoals),
    homeGoals,
    awayGoals,
    valid
  };
}

function splitFixtureLabel(label) {
  const cleaned = toText(label).replace(/\s+vs\s+/i, '-');
  if (!cleaned.includes('-')) return { home: '', away: '' };
  const parts = cleaned.split('-');
  return { home: parts[0].trim(), away: parts.slice(1).join('-').trim() };
}

function uniqueByTeam(values) {
  const seen = new Set();
  const out = [];
  for (const value of values || []) {
    if (!isRealTeam(value)) continue;
    const key = teamKey(value);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(canonicalTeamName(value));
  }
  return out;
}

function containsTeam(list, value) {
  const key = teamKey(value);
  if (!key) return false;
  return (list || []).some((item) => teamKey(item) === key);
}

function safeReadJson(file, fallback) {
  try {
    return require('fs').existsSync(file) ? JSON.parse(require('fs').readFileSync(file, 'utf8')) : fallback;
  } catch (err) {
    return fallback;
  }
}

module.exports = {
  toText,
  normalizeText,
  canonicalTeamName,
  teamKey,
  sameTeam,
  isPlaceholderTeam,
  isRealTeam,
  asNumber,
  signFromScores,
  goalDiff,
  parseScorePrediction,
  splitFixtureLabel,
  uniqueByTeam,
  containsTeam,
  safeReadJson
};

    },
    "./apiClient": function (require, module, exports) {
const fs = require('fs');
const path = require('path');
const { asNumber, normalizeText, toText, canonicalTeamName } = require('./utils');

function readPath(obj, paths) {
  for (const p of paths) {
    const parts = p.split('.');
    let cur = obj;
    for (const part of parts) {
      if (cur === null || cur === undefined) break;
      cur = cur[part];
    }
    if (cur !== null && cur !== undefined && cur !== '') return cur;
  }
  return null;
}

function findFirstArray(value, preferredKeys = []) {
  if (Array.isArray(value)) return value;
  if (!value || typeof value !== 'object') return [];
  for (const key of preferredKeys) {
    if (Array.isArray(value[key])) return value[key];
    if (value.data && Array.isArray(value.data[key])) return value.data[key];
  }
  if (Array.isArray(value.data)) return value.data;
  for (const child of Object.values(value)) {
    if (Array.isArray(child) && child.length && typeof child[0] === 'object') return child;
  }
  for (const child of Object.values(value)) {
    const arr = findFirstArray(child, preferredKeys);
    if (arr.length) return arr;
  }
  return [];
}

function normalizeTeamObject(team) {
  if (!team) return '';
  if (typeof team === 'string') return canonicalTeamName(team);
  return canonicalTeamName(
    readPath(team, ['name_es', 'nameEn', 'name_en', 'name', 'teamName', 'country', 'title', 'shortName'])
  );
}

function getTeamFromMatch(game, side) {
  const sideTitle = side === 'home' ? 'home' : 'away';
  const alt = side === 'home' ? 'team1' : 'team2';
  const candidate = readPath(game, [
    `${sideTitle}Team.name`, `${sideTitle}Team.name_en`, `${sideTitle}Team.nameEn`,
    `${sideTitle}_team.name`, `${sideTitle}_team.name_en`, `${sideTitle}_team`,
    `${sideTitle}.name`, `${sideTitle}`,
    `${sideTitle}TeamName`, `${sideTitle}_team_name`, `${sideTitle}Name`,
    `${sideTitle}_team_name_en`, `${sideTitle}_team_name_fa`,
    `${alt}.name`, `${alt}`,
    `teams.${sideTitle}.name`, `teams.${sideTitle}`
  ]);
  return normalizeTeamObject(candidate);
}

function getScoreFromMatch(game, side) {
  const prefix = side === 'home' ? 'home' : 'away';
  const altPrefix = side === 'home' ? 'team1' : 'team2';
  return asNumber(readPath(game, [
    `${prefix}Score`, `${prefix}_score`, `${prefix}Goals`, `${prefix}_goals`, `${prefix}_goals_full_time`,
    `score.${prefix}`, `scores.${prefix}`, `score.fullTime.${prefix}`, `score.ft.${prefix}`,
    `goals.${prefix}`, `result.${prefix}`, `${altPrefix}Score`, `${altPrefix}_score`,
    side === 'home' ? 'score1' : 'score2',
    side === 'home' ? 'home_score_current' : 'away_score_current'
  ]));
}

function inferStage(game, matchNumber) {
  const text = normalizeText([
    readPath(game, ['stage', 'round', 'phase', 'matchType', 'type', 'groupName', 'group.name']),
    readPath(game, ['name', 'title', 'description'])
  ].filter(Boolean).join(' '));

  if (matchNumber >= 1 && matchNumber <= 72) return 'group';
  if (matchNumber >= 73 && matchNumber <= 88) return 'round32';
  if (matchNumber >= 89 && matchNumber <= 96) return 'round16';
  if (matchNumber >= 97 && matchNumber <= 100) return 'quarter';
  if (matchNumber >= 101 && matchNumber <= 102) return 'semi';
  if (matchNumber === 103) return 'third';
  if (matchNumber === 104) return 'final';

  if (text.includes('group')) return 'group';
  if (text.includes('round of 32') || text.includes('dieciseis')) return 'round32';
  if (text.includes('round of 16') || text.includes('octav')) return 'round16';
  if (text.includes('quarter') || text.includes('cuarto')) return 'quarter';
  if (text.includes('semi')) return 'semi';
  if (text.includes('third') || text.includes('3')) return 'third';
  if (text.includes('final')) return 'final';
  return 'unknown';
}

function inferGroup(game) {
  const raw = readPath(game, ['group', 'groupName', 'group_name', 'group.name', 'pool', 'poolName']);
  const text = toText(raw);
  const match = text.match(/([A-L])/i);
  return match ? match[1].toUpperCase() : '';
}

function isFinishedStatus(statusRaw) {
  if (statusRaw === true) return true;
  if (statusRaw === false) return false;
  const status = normalizeText(statusRaw);
  if (!status) return false;
  if (['true', '1', 'yes'].includes(status)) return true;
  if (['false', '0', 'no', 'notstarted', 'not started'].includes(status)) return false;
  return /(finished|full time|fulltime|ft|played|complete|completed|ended|finalizado|terminado|after extra|aet|penalties|penalty)/.test(status);
}

const STADIUM_UTC_OFFSETS = {
  // Mexico does not use DST in these host cities; World Cup 2026 is in June.
  1: -6, 2: -6, 3: -6,
  // US Central daylight time.
  4: -5, 5: -5, 6: -5,
  // US/Canada Eastern daylight time.
  7: -4, 8: -4, 9: -4, 10: -4, 11: -4, 12: -4,
  // US/Canada Pacific daylight time.
  13: -7, 14: -7, 15: -7, 16: -7
};

function parseVenueLocalKickoff(value, stadiumId) {
  const raw = toText(value);
  const match = raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2})$/);
  const offset = STADIUM_UTC_OFFSETS[Number(stadiumId)];
  if (!match || offset === undefined) return raw;
  const [, month, day, year, hour, minute] = match;
  return new Date(Date.UTC(
    Number(year),
    Number(month) - 1,
    Number(day),
    Number(hour) - offset,
    Number(minute)
  )).toISOString();
}

function getKickoff(game) {
  const local = readPath(game, ['local_date', 'localDate']);
  if (local) return parseVenueLocalKickoff(local, readPath(game, ['stadium_id', 'stadiumId', 'stadium.id']));
  return toText(readPath(game, ['date', 'datetime', 'startTime', 'start_time', 'kickoff', 'utcDate']) || '');
}

function normalizeGames(raw) {
  const arr = findFirstArray(raw, ['games', 'matches', 'fixtures', 'data']);
  const sorted = [...arr].sort((a, b) => {
    const na = asNumber(readPath(a, ['matchNumber', 'match_number', 'number', 'gameNumber', 'game_number', 'id']));
    const nb = asNumber(readPath(b, ['matchNumber', 'match_number', 'number', 'gameNumber', 'game_number', 'id']));
    if (na !== null && nb !== null) return na - nb;
    const da = Date.parse(getKickoff(a) || '');
    const db = Date.parse(getKickoff(b) || '');
    if (Number.isFinite(da) && Number.isFinite(db)) return da - db;
    return 0;
  });

  return sorted.map((game, index) => {
    const explicitNumber = asNumber(readPath(game, ['matchNumber', 'match_number', 'number', 'gameNumber', 'game_number']));
    const matchNumber = explicitNumber || index + 1;
    const statusRaw = readPath(game, ['status', 'state', 'matchStatus', 'match_status', 'finished', 'time_elapsed']);
    const homeScore = getScoreFromMatch(game, 'home');
    const awayScore = getScoreFromMatch(game, 'away');
    return {
      raw: game,
      matchNumber,
      stage: inferStage(game, matchNumber),
      group: inferGroup(game),
      homeTeam: getTeamFromMatch(game, 'home'),
      awayTeam: getTeamFromMatch(game, 'away'),
      homeScore,
      awayScore,
      status: toText(statusRaw || ''),
      finished: isFinishedStatus(statusRaw),
      winnerTeam: normalizeTeamObject(readPath(game, ['winner.name', 'winner', 'winnerTeam.name', 'winner_team.name', 'winnerTeam', 'winner_team'])),
      loserTeam: normalizeTeamObject(readPath(game, ['loser.name', 'loser', 'loserTeam.name', 'loser_team.name', 'loserTeam', 'loser_team'])),
      venue: toText(readPath(game, ['venue.name', 'stadium.name', 'stadium', 'venue', 'location']) || ''),
      kickoff: getKickoff(game),
      title: toText(readPath(game, ['name', 'title']) || '')
    };
  });
}

function normalizeGroups(raw) {
  const arr = findFirstArray(raw, ['groups', 'standings', 'tables', 'data']);
  const groups = {};

  function addTeam(groupLetter, team, idx) {
    if (!groupLetter || !team) return;
    if (!groups[groupLetter]) groups[groupLetter] = [];
    groups[groupLetter].push({
      team: normalizeTeamObject(team),
      position: asNumber(readPath(team, ['position', 'rank', 'standing'])) || idx + 1,
      points: asNumber(readPath(team, ['points', 'pts', 'point'])) || 0,
      goalDifference: asNumber(readPath(team, ['goalDifference', 'goal_difference', 'gd', 'diff'])) || 0,
      goalsFor: asNumber(readPath(team, ['goalsFor', 'goals_for', 'gf'])) || 0,
      goalsAgainst: asNumber(readPath(team, ['goalsAgainst', 'goals_against', 'ga'])) || 0
    });
  }

  for (const item of arr) {
    const groupLetter = inferGroup(item);
    const teams = findFirstArray(item, ['teams', 'standings', 'table']);
    if (teams.length) {
      teams.forEach((team, i) => addTeam(groupLetter, team, i));
    } else if (groupLetter) {
      addTeam(groupLetter, item, groups[groupLetter]?.length || 0);
    }
  }

  for (const [group, teams] of Object.entries(groups)) {
    groups[group] = teams.filter((t) => t.team).sort((a, b) => a.position - b.position);
  }

  return groups;
}

function normalizeTeams(raw) {
  const arr = findFirstArray(raw, ['teams', 'data']);
  return arr.map(normalizeTeamObject).filter(Boolean);
}

function normalizeApiData(raw) {
  return {
    games: normalizeGames(raw.gamesRaw || raw.games || raw.matches || []),
    groups: normalizeGroups(raw.groupsRaw || raw.groups || []),
    teams: normalizeTeams(raw.teamsRaw || raw.teams || []),
    fetchedAt: raw.fetchedAt || new Date().toISOString(),
    source: raw.source || 'cache/manual'
  };
}

async function fetchJson(url, timeoutMs = 12000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { signal: controller.signal, headers: { 'accept': 'application/json' } });
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

async function fetchWorldCupData(options = {}) {
  const base = (options.baseUrl || process.env.WORLD_CUP_API_BASE || 'https://worldcup26.ir').replace(/\/$/, '');
  const cacheFile = path.resolve(process.cwd(), options.cacheFile || process.env.CACHE_FILE || './data/cache/current-api.json');
  fs.mkdirSync(path.dirname(cacheFile), { recursive: true });

  try {
    const [gamesRaw, groupsRaw, teamsRaw] = await Promise.all([
      fetchJson(`${base}/get/games`),
      fetchJson(`${base}/get/groups`).catch(() => []),
      fetchJson(`${base}/get/teams`).catch(() => [])
    ]);
    const payload = { gamesRaw, groupsRaw, teamsRaw, fetchedAt: new Date().toISOString(), source: base };
    fs.writeFileSync(cacheFile, JSON.stringify(payload, null, 2));
    return normalizeApiData(payload);
  } catch (err) {
    if (fs.existsSync(cacheFile)) {
      const cached = JSON.parse(fs.readFileSync(cacheFile, 'utf8'));
      const normalized = normalizeApiData({ ...cached, source: `${cached.source || base} (cache)` });
      normalized.apiWarning = `No se pudo refrescar la API: ${err.message}. Usando caché.`;
      return normalized;
    }
    return {
      games: [],
      groups: {},
      teams: [],
      fetchedAt: new Date().toISOString(),
      source: base,
      apiWarning: `No se pudo consultar la API y no hay caché: ${err.message}`
    };
  }
}

module.exports = {
  fetchWorldCupData,
  normalizeApiData,
  normalizeGames,
  normalizeGroups,
  normalizeTeams
};

    },
    "./scoring": function (require, module, exports) {
const { POINTS, STAGE_LABELS } = require('./config');
const {
  asNumber,
  signFromScores,
  goalDiff,
  containsTeam,
  isRealTeam,
  sameTeam,
  teamKey,
  canonicalTeamName,
  uniqueByTeam,
  normalizeText
} = require('./utils');

function buildMatchMap(games) {
  const map = new Map();
  for (const game of games || []) {
    if (game.matchNumber) map.set(Number(game.matchNumber), game);
  }
  return map;
}

function predictedTeams(prediction) {
  return {
    home: prediction.prefix ? prediction.prefix.split('-')[0] : prediction.homeLabel,
    away: prediction.prefix ? prediction.prefix.split('-').slice(1).join('-') : prediction.awayLabel
  };
}

function matchTeamsPrediction(prediction, actual) {
  const teams = predictedTeams(prediction);
  const includesRealTeams = isRealTeam(teams.home) && isRealTeam(teams.away);
  return !includesRealTeams || (sameTeam(teams.home, actual?.homeTeam) && sameTeam(teams.away, actual?.awayTeam));
}

function findActualMatchForPrediction(prediction, actual) {
  const byNumber = actual.matchMap.get(Number(prediction.matchNumber));
  if (byNumber && matchTeamsPrediction(prediction, byNumber)) return byNumber;

  const teams = predictedTeams(prediction);
  if (!isRealTeam(teams.home) || !isRealTeam(teams.away)) return byNumber;

  return (actual.games || []).find((match) =>
    match.stage === prediction.stage &&
    sameTeam(teams.home, match.homeTeam) &&
    sameTeam(teams.away, match.awayTeam)
  ) || byNumber;
}

function winnerFromMatch(match) {
  if (!match || !match.finished) return '';
  if (match.winnerTeam) return canonicalTeamName(match.winnerTeam);
  const h = asNumber(match.homeScore);
  const a = asNumber(match.awayScore);
  if (h === null || a === null || h === a) return '';
  return h > a ? match.homeTeam : match.awayTeam;
}

function loserFromMatch(match) {
  if (!match || !match.finished) return '';
  if (match.loserTeam) return canonicalTeamName(match.loserTeam);
  const h = asNumber(match.homeScore);
  const a = asNumber(match.awayScore);
  if (h === null || a === null || h === a) return '';
  return h > a ? match.awayTeam : match.homeTeam;
}

function stageForMatchNumber(matchNumber) {
  if (matchNumber <= 72) return 'group';
  if (matchNumber <= 88) return 'round32';
  if (matchNumber <= 96) return 'round16';
  if (matchNumber <= 100) return 'quarter';
  if (matchNumber <= 102) return 'semi';
  if (matchNumber === 103) return 'third';
  if (matchNumber === 104) return 'final';
  return 'unknown';
}

function scoreMatchPrediction(prediction, actual) {
  const stage = prediction.stage || stageForMatchNumber(prediction.matchNumber);
  const rules = POINTS.match[stage] || { sign: 0, goalDiff: 0, exact: 0 };
  const details = [];

  if (!prediction?.valid || !actual?.finished) {
    return { points: 0, max: Math.max(rules.exact || 0, rules.sign || 0), details, status: 'pending' };
  }

  const actualSign = signFromScores(actual.homeScore, actual.awayScore);
  const exact = prediction.homeGoals === actual.homeScore && prediction.awayGoals === actual.awayScore;
  const sign = prediction.sign === actualSign;
  const diff = goalDiff(prediction.homeGoals, prediction.awayGoals) === goalDiff(actual.homeScore, actual.awayScore);

  // Evita dar puntos de marcador en eliminatorias si la predicción incluye equipos reales distintos del partido real.
  const teamsMatch = matchTeamsPrediction(prediction, actual);

  let points = 0;
  if (exact && teamsMatch) {
    points = rules.exact || 0;
    if (points) details.push(`Resultado exacto: +${points}`);
  } else if (sign && teamsMatch) {
    points = rules.sign || 0;
    if (points) details.push(`Signo 1X2: +${points}`);
    if (diff && rules.goalDiff) {
      points += rules.goalDiff;
      details.push(`Diferencia de goles: +${rules.goalDiff}`);
    }
  }

  return {
    points,
    max: Math.max(rules.exact || 0, rules.sign || 0),
    details,
    status: points > 0 ? 'hit' : 'miss',
    exact,
    sign,
    teamsMatch
  };
}

function computeGroupStandings(games) {
  const standings = {};
  const completedByGroup = {};

  function ensure(group, team) {
    if (!group || !team) return null;
    if (!standings[group]) standings[group] = new Map();
    const key = teamKey(team);
    if (!standings[group].has(key)) {
      standings[group].set(key, {
        team: canonicalTeamName(team),
        played: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalDifference: 0
      });
    }
    return standings[group].get(key);
  }

  for (const match of games || []) {
    if (match.stage !== 'group' || !match.group || !match.finished) continue;
    const home = ensure(match.group, match.homeTeam);
    const away = ensure(match.group, match.awayTeam);
    const h = asNumber(match.homeScore);
    const a = asNumber(match.awayScore);
    if (!home || !away || h === null || a === null) continue;
    home.played += 1;
    away.played += 1;
    home.goalsFor += h;
    home.goalsAgainst += a;
    away.goalsFor += a;
    away.goalsAgainst += h;
    home.goalDifference = home.goalsFor - home.goalsAgainst;
    away.goalDifference = away.goalsFor - away.goalsAgainst;
    if (h > a) home.points += 3;
    else if (h < a) away.points += 3;
    else {
      home.points += 1;
      away.points += 1;
    }
    completedByGroup[match.group] = (completedByGroup[match.group] || 0) + 1;
  }

  const out = {};
  for (const [group, map] of Object.entries(standings)) {
    out[group] = [...map.values()].sort((a, b) =>
      b.points - a.points || b.goalDifference - a.goalDifference || b.goalsFor - a.goalsFor || a.team.localeCompare(b.team)
    ).map((team, idx) => ({ ...team, position: idx + 1 }));
  }
  return { standings: out, completedByGroup };
}

function mergeApiAndComputedGroups(apiGroups, computed) {
  const out = { ...(computed.standings || {}) };
  for (const [group, rows] of Object.entries(apiGroups || {})) {
    if (rows?.length) out[group] = rows;
  }
  return out;
}

function allGroupMatchesCompleted(completedByGroup) {
  return Array.from({ length: 12 }, (_, i) => String.fromCharCode(65 + i)).every((group) => (completedByGroup[group] || 0) >= 6);
}

function qualifiedRound32FromGroups(groups, completedByGroup) {
  if (!allGroupMatchesCompleted(completedByGroup)) return [];
  const groupLetters = Array.from({ length: 12 }, (_, i) => String.fromCharCode(65 + i));
  const topTwo = [];
  const thirds = [];
  for (const group of groupLetters) {
    const table = groups[group] || [];
    if (table.length < 4) return [];
    topTwo.push(table[0]?.team, table[1]?.team);
    thirds.push({ group, ...(table[2] || {}) });
  }
  const bestThirds = thirds
    .filter((t) => t.team)
    .sort((a, b) => b.points - a.points || b.goalDifference - a.goalDifference || b.goalsFor - a.goalsFor || a.team.localeCompare(b.team))
    .slice(0, 8)
    .map((t) => t.team);
  return uniqueByTeam([...topTwo, ...bestThirds]);
}

function winnersForRange(matchMap, start, end) {
  const winners = [];
  for (let n = start; n <= end; n++) {
    const winner = winnerFromMatch(matchMap.get(n));
    if (winner) winners.push(winner);
  }
  return uniqueByTeam(winners);
}

function losersForRange(matchMap, start, end) {
  const losers = [];
  for (let n = start; n <= end; n++) {
    const loser = loserFromMatch(matchMap.get(n));
    if (loser) losers.push(loser);
  }
  return uniqueByTeam(losers);
}

function buildActualFacts(apiData) {
  const games = apiData.games || [];
  const matchMap = buildMatchMap(games);
  const computed = computeGroupStandings(games);
  const groups = mergeApiAndComputedGroups(apiData.groups, computed);
  const completedByGroup = computed.completedByGroup || {};

  const actual = {
    games,
    matchMap,
    groups,
    completedByGroup,
    qualified: {
      round32: qualifiedRound32FromGroups(groups, completedByGroup),
      round16: winnersForRange(matchMap, 73, 88),
      quarter: winnersForRange(matchMap, 89, 96),
      semi: winnersForRange(matchMap, 97, 100),
      thirdPlaceGame: losersForRange(matchMap, 101, 102),
      final: winnersForRange(matchMap, 101, 102)
    },
    podium: {
      champion: winnerFromMatch(matchMap.get(104)),
      runnerUp: loserFromMatch(matchMap.get(104)),
      thirdPlace: winnerFromMatch(matchMap.get(103))
    }
  };

  return actual;
}

function scoreTeamList(predictions, actualList, pointsPerHit, label) {
  let points = 0;
  const hits = [];
  const misses = [];
  for (const pred of predictions || []) {
    if (!pred.team) continue;
    if (containsTeam(actualList, pred.team)) {
      points += pointsPerHit;
      hits.push(pred.team);
    } else {
      misses.push(pred.team);
    }
  }
  return { points, hits, misses, label, max: (predictions || []).filter((p) => p.team).length * pointsPerHit };
}

function scoreGroupPositions(participant, actual) {
  let points = 0;
  const rows = [];
  for (const pred of participant.predictions.groupPositions || []) {
    if (!pred.team || (actual.completedByGroup[pred.group] || 0) < 6) continue;
    const table = actual.groups[pred.group] || [];
    const actualTeam = table[pred.position - 1]?.team;
    const hit = actualTeam && sameTeam(pred.team, actualTeam);
    if (hit) points += POINTS.groupPosition;
    rows.push({
      group: pred.group,
      position: pred.position,
      prediction: pred.team,
      actual: actualTeam || '',
      points: hit ? POINTS.groupPosition : 0
    });
  }
  return { points, rows };
}

function scorePodium(participant, actual) {
  const checks = [
    ['champion', POINTS.champion, 'Campeón'],
    ['runnerUp', POINTS.runnerUp, 'Subcampeón'],
    ['thirdPlace', POINTS.thirdPlace, '3º puesto']
  ];
  let points = 0;
  const rows = [];
  for (const [key, pts, label] of checks) {
    const pred = participant.predictions.podium[key]?.team;
    const real = actual.podium[key];
    const hit = pred && real && sameTeam(pred, real);
    if (hit) points += pts;
    rows.push({ label, prediction: pred || '', actual: real || '', points: hit ? pts : 0 });
  }
  return { points, rows };
}

function normalizePlayer(value) {
  return normalizeText(String(value || '').replace(/\([^)]*\)/g, ''));
}

function scoreAwards(participant, manualAwards) {
  let points = 0;
  const rows = [];
  const checks = [
    ['goldenBoot', 'gold', POINTS.goldenBoot.gold, 'Bota de Oro'],
    ['goldenBoot', 'silver', POINTS.goldenBoot.silver, 'Bota de Plata'],
    ['goldenBoot', 'bronze', POINTS.goldenBoot.bronze, 'Bota de Bronce'],
    ['goldenBall', 'gold', POINTS.goldenBall.gold, 'Balón de Oro'],
    ['goldenBall', 'silver', POINTS.goldenBall.silver, 'Balón de Plata'],
    ['goldenBall', 'bronze', POINTS.goldenBall.bronze, 'Balón de Bronce']
  ];

  for (const [award, medal, pts, label] of checks) {
    const pred = participant.predictions.awards?.[award]?.[medal]?.name || '';
    const actualList = (manualAwards?.[award] || []).map(normalizePlayer).filter(Boolean);
    const hit = pts > 0 && pred && actualList.includes(normalizePlayer(pred));
    if (hit) points += pts;
    rows.push({ label, prediction: pred, actual: (manualAwards?.[award] || []).join(', '), points: hit ? pts : 0 });
  }
  return { points, rows };
}

function scoreParticipant(participant, apiData, manualAwards = {}) {
  const actual = buildActualFacts(apiData);
  const breakdown = Object.fromEntries(Object.keys(STAGE_LABELS).map((key) => [key, 0]));
  const events = [];
  const matchTimeline = [];
  let total = 0;

  for (const [matchNumberRaw, prediction] of Object.entries(participant.predictions.matches || {})) {
    const matchNumber = Number(matchNumberRaw);
    const actualMatch = findActualMatchForPrediction(prediction, actual);
    const score = scoreMatchPrediction(prediction, actualMatch);
    if (actualMatch?.finished && prediction?.valid) {
      matchTimeline.push({
        matchNumber: actualMatch.matchNumber || matchNumber,
        label: `${actualMatch.homeTeam || prediction.homeLabel} - ${actualMatch.awayTeam || prediction.awayLabel}`,
        points: score.points || 0,
        exact: Boolean(score.exact && score.teamsMatch)
      });
    }
    if (score.points) {
      total += score.points;
      breakdown[prediction.stage] += score.points;
      events.push({
        type: 'match',
        stage: prediction.stage,
        matchNumber: actualMatch?.matchNumber || matchNumber,
        label: `${actualMatch?.homeTeam || prediction.homeLabel} - ${actualMatch?.awayTeam || prediction.awayLabel}`,
        prediction: prediction.valid ? `${prediction.homeGoals}-${prediction.awayGoals}` : prediction.raw,
        actual: actualMatch?.finished ? `${actualMatch.homeScore}-${actualMatch.awayScore}` : '',
        points: score.points,
        details: score.details.join(', ')
      });
    }
  }

  const groupPosition = scoreGroupPositions(participant, actual);
  total += groupPosition.points;
  breakdown.group += groupPosition.points;
  groupPosition.rows.filter((r) => r.points).forEach((r) => events.push({
    type: 'groupPosition', stage: 'group', label: `${r.position}º Grupo ${r.group}`, prediction: r.prediction, actual: r.actual, points: r.points
  }));

  const qualifierChecks = [
    ['round32', POINTS.qualifiedRound32, 'Clasificado para dieciseisavos', 'group'],
    ['round16', POINTS.qualifiedRound16, 'Clasificado para octavos', 'round32'],
    ['quarter', POINTS.qualifiedQuarter, 'Clasificado para cuartos', 'round16'],
    ['semi', POINTS.qualifiedSemi, 'Clasificado para semifinales', 'quarter'],
    ['thirdPlaceGame', POINTS.qualifiedThirdPlaceGame, 'Clasificado para 3º/4º puesto', 'semi'],
    ['final', POINTS.qualifiedFinal, 'Clasificado para la final', 'semi']
  ];

  for (const [key, pts, label, stageBucket] of qualifierChecks) {
    const res = scoreTeamList(participant.predictions.qualifiers[key], actual.qualified[key], pts, label);
    total += res.points;
    breakdown[stageBucket] += res.points;
    res.hits.forEach((team) => events.push({ type: 'qualifier', stage: stageBucket, label, prediction: team, actual: team, points: pts }));
  }

  const podium = scorePodium(participant, actual);
  total += podium.points;
  breakdown.honor += podium.points;
  podium.rows.filter((r) => r.points).forEach((r) => events.push({ type: 'podium', stage: 'honor', ...r }));

  const awards = scoreAwards(participant, manualAwards);
  total += awards.points;
  breakdown.awards += awards.points;
  awards.rows.filter((r) => r.points).forEach((r) => events.push({ type: 'award', stage: 'awards', ...r }));

  const exactScores = events.filter((e) => e.type === 'match' && String(e.details || '').includes('Resultado exacto')).length;
  return {
    id: participant.id,
    name: participant.name,
    file: participant.file,
    total,
    breakdown,
    exactScores,
    hits: events.length,
    timeline: matchTimeline.sort((a, b) => a.matchNumber - b.matchNumber),
    events: events.sort((a, b) => (b.points || 0) - (a.points || 0)).slice(0, 30)
  };
}

function makeLeaderboard(participants, apiData, manualAwards = {}) {
  const scores = participants.map((p) => scoreParticipant(p, apiData, manualAwards));
  scores.sort((a, b) => b.total - a.total || b.exactScores - a.exactScores || a.name.localeCompare(b.name));
  return scores.map((row, idx) => ({ ...row, rank: idx + 1 }));
}

function makeFunFacts(leaderboard, participants, apiData) {
  const facts = [];
  const actual = buildActualFacts(apiData);
  const leader = leaderboard[0];
  if (leader) facts.push({ title: 'Líder provisional', value: leader.name, meta: `${leader.total} puntos` });

  const championPicks = new Map();
  for (const p of participants) {
    const champ = p.predictions.podium.champion?.team;
    if (!champ) continue;
    championPicks.set(champ, (championPicks.get(champ) || 0) + 1);
  }
  const popular = [...championPicks.entries()].sort((a, b) => b[1] - a[1])[0];
  if (popular) facts.push({ title: 'Campeón más apostado', value: popular[0], meta: `${popular[1]} participantes` });

  const unpopular = [...championPicks.entries()].sort((a, b) => a[1] - b[1])[0];
  if (unpopular && unpopular !== popular) facts.push({ title: 'Apuesta diferencial', value: unpopular[0], meta: `${unpopular[1]} participante(s)` });

  const exactKing = [...leaderboard].sort((a, b) => b.exactScores - a.exactScores)[0];
  if (exactKing) facts.push({ title: 'Rey del marcador exacto', value: exactKing.name, meta: `${exactKing.exactScores} exactos` });

  const finished = (apiData.games || []).filter((m) => m.finished).length;
  facts.push({ title: 'Partidos computados', value: finished, meta: 'de 104' });

  if (actual.podium.champion) facts.push({ title: 'Campeón real', value: actual.podium.champion, meta: 'cuadro de honor cerrado' });
  return facts;
}

function fallbackMatchesFromPredictions(participants) {
  const first = participants?.[0];
  if (!first?.predictions?.matches) return [];
  return Object.values(first.predictions.matches).map((p) => ({
    matchNumber: p.matchNumber,
    stage: p.stage,
    group: p.stage === 'group' && p.label ? (p.label.match(/^([A-L])/)?.[1] || '') : '',
    homeTeam: p.homeLabel,
    awayTeam: p.awayLabel,
    homeScore: null,
    awayScore: null,
    status: 'Pendiente',
    finished: false,
    kickoff: '',
    venue: ''
  }));
}

function scoreDashboard(participants, apiData, manualAwards = {}) {
  const leaderboard = makeLeaderboard(participants, apiData, manualAwards);
  const actual = buildActualFacts(apiData);
  const apiMatches = (apiData.games || []).map((m) => ({
    matchNumber: m.matchNumber,
    stage: m.stage,
    group: m.group,
    homeTeam: m.homeTeam,
    awayTeam: m.awayTeam,
    homeScore: m.homeScore,
    awayScore: m.awayScore,
    status: m.status,
    finished: m.finished,
    kickoff: m.kickoff,
    venue: m.venue
  }));
  return {
    leaderboard,
    funFacts: makeFunFacts(leaderboard, participants, apiData),
    stages: STAGE_LABELS,
    points: POINTS,
    actual: {
      groups: actual.groups,
      completedByGroup: actual.completedByGroup,
      qualified: actual.qualified,
      podium: actual.podium,
      matches: apiMatches.length ? apiMatches : fallbackMatchesFromPredictions(participants)
    }
  };
}

module.exports = {
  scoreDashboard,
  makeLeaderboard,
  buildActualFacts,
  computeGroupStandings,
  scoreParticipant
};

    }
  };
  const cache = {};
  function require(id) {
    if (id === 'fs') return {};
    if (id === 'path') return { resolve: (...parts) => parts.filter(Boolean).join('/'), dirname: (file) => String(file).split('/').slice(0, -1).join('/') };
    if (!sources[id]) throw new Error('Static bundle cannot resolve module: ' + id);
    if (!cache[id]) {
      const module = { exports: {} };
      cache[id] = module;
      sources[id](require, module, module.exports);
    }
    return cache[id].exports;
  }
  const apiClient = require('./apiClient');
  const scoring = require('./scoring');
  window.PorraEngine = {
    normalizeApiData: apiClient.normalizeApiData,
    scoreDashboard: scoring.scoreDashboard
  };
}());
