const fs = require('fs');
const path = require('path');
const { readParticipants } = require('../server/excelImporter');
const { fetchWorldCupData } = require('../server/apiClient');
const { safeReadJson } = require('../server/utils');

const ROOT = path.resolve(__dirname, '..');
const PUBLIC_DIR = path.join(ROOT, 'public');
const DOCS_DIR = path.join(ROOT, 'docs');
const PREDICTIONS_DIR = path.join(ROOT, 'data/predictions');
const MANUAL_AWARDS_FILE = path.join(ROOT, 'data/manual/awards.json');
const CACHE_FILE = path.join(ROOT, 'data/cache/current-api.json');
const STATIC_FILES = [
  '.nojekyll',
  'app.js',
  'index.html',
  'static-data.json',
  'static-engine.js',
  'styles.css'
];

function readSource(relativePath) {
  return fs.readFileSync(path.join(ROOT, relativePath), 'utf8');
}

function jsString(value) {
  return JSON.stringify(value);
}

function buildBrowserEngine() {
  const modules = {
    './config': readSource('server/config.js'),
    './utils': readSource('server/utils.js'),
    './apiClient': readSource('server/apiClient.js'),
    './scoring': readSource('server/scoring.js')
  };

  const bundle = `// Generated by scripts/build-pages.js. Do not edit by hand.
(function () {
  const sources = {
${Object.entries(modules).map(([id, source]) => `    ${jsString(id)}: function (require, module, exports) {\n${source}\n    }`).join(',\n')}
  };
  const cache = {};
  function require(id) {
    if (id === 'fs') return {};
    if (id === 'path') return { resolve: (...parts) => parts.filter(Boolean).join('/'), dirname: (file) => String(file).split('/').slice(0, -1).join('/') };
    if (!sources[id]) throw new Error('Static bundle cannot resolve module: ' + id);
    if (!cache[id]) {
      const module = { exports: {} };
      cache[id] = module;
      sources[id](require, module, module.exports);
    }
    return cache[id].exports;
  }
  const apiClient = require('./apiClient');
  const scoring = require('./scoring');
  window.PorraEngine = {
    normalizeApiData: apiClient.normalizeApiData,
    scoreDashboard: scoring.scoreDashboard
  };
}());
`;

  fs.writeFileSync(path.join(PUBLIC_DIR, 'static-engine.js'), bundle);
}

async function buildStaticData() {
  const { participants, errors } = readParticipants(PREDICTIONS_DIR);
  const manualAwards = safeReadJson(MANUAL_AWARDS_FILE, { goldenBoot: [], goldenBall: [] });
  const apiData = await fetchWorldCupData({ cacheFile: CACHE_FILE });

  const payload = {
    generatedAt: new Date().toISOString(),
    participants,
    importErrors: errors,
    manualAwards,
    apiData
  };

  fs.writeFileSync(path.join(PUBLIC_DIR, 'static-data.json'), JSON.stringify(payload, null, 2));
  console.log(`GitHub Pages data generated: ${participants.length} participante(s), ${errors.length} error(es)`);
}

function copyStaticSiteToDocs() {
  fs.mkdirSync(DOCS_DIR, { recursive: true });
  for (const file of STATIC_FILES) {
    fs.copyFileSync(path.join(PUBLIC_DIR, file), path.join(DOCS_DIR, file));
  }
  console.log('Static site copied to docs/ for branch-based GitHub Pages.');
}

function copyStaticSiteToRoot() {
  for (const file of STATIC_FILES) {
    fs.copyFileSync(path.join(PUBLIC_DIR, file), path.join(ROOT, file));
  }
  console.log('Static site copied to repo root for user GitHub Pages.');
}

async function main() {
  buildBrowserEngine();
  await buildStaticData();
  copyStaticSiteToDocs();
  copyStaticSiteToRoot();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
